// Date: 6/12/2014 12:37:57 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package net.richardsprojects.rep.model;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;

public class ModelFlagPoleWithPennant extends ModelBase
{
   //fields
    ModelRenderer pole;
    ModelRenderer base;
    ModelRenderer top2;
    ModelRenderer top1;
    ModelRenderer top3;
    ModelRenderer TriangularFlagPart1;
    ModelRenderer TriangularFlagPart2;
    ModelRenderer TriangularFlagPart3;
    ModelRenderer TriangularFlagPart4;
    ModelRenderer TriangularFlagPart5;
    ModelRenderer TriangularFlagPart6;
  
  public ModelFlagPoleWithPennant()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      pole = new ModelRenderer(this, 0, 0);
      pole.addBox(0F, 0F, 0F, 3, 28, 3);
      pole.setRotationPoint(-2F, -4F, -2F);
      pole.setTextureSize(64, 32);
      pole.mirror = true;
      setRotation(pole, 0F, 0F, 0F);
      base = new ModelRenderer(this, 0, 0);
      base.addBox(0F, 0F, 0F, 7, 1, 7);
      base.setRotationPoint(-4F, 23F, -4F);
      base.setTextureSize(64, 32);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      top2 = new ModelRenderer(this, 0, 0);
      top2.addBox(0F, 0F, 0F, 5, 1, 5);
      top2.setRotationPoint(-3F, -5F, -3F);
      top2.setTextureSize(64, 32);
      top2.mirror = true;
      setRotation(top2, 0F, 0F, 0F);
      top1 = new ModelRenderer(this, 0, 0);
      top1.addBox(0F, 0F, 0F, 4, 1, 4);
      top1.setRotationPoint(-2.5F, -4F, -2.5F);
      top1.setTextureSize(64, 32);
      top1.mirror = true;
      setRotation(top1, 0F, 0F, 0F);
      top3 = new ModelRenderer(this, 0, 0);
      top3.addBox(0F, 0F, 0F, 4, 1, 4);
      top3.setRotationPoint(-2.5F, -6F, -2.5F);
      top3.setTextureSize(64, 32);
      top3.mirror = true;
      setRotation(top3, 0F, 0F, 0F);
      TriangularFlagPart1 = new ModelRenderer(this, 0, 0);
      TriangularFlagPart1.addBox(0F, 0F, 0F, 3, 9, 1);
      TriangularFlagPart1.setRotationPoint(-5F, -2F, -1F);
      TriangularFlagPart1.setTextureSize(64, 32);
      TriangularFlagPart1.mirror = true;
      setRotation(TriangularFlagPart1, 0F, 0F, 0F);
      TriangularFlagPart2 = new ModelRenderer(this, 0, 0);
      TriangularFlagPart2.addBox(0F, 0F, 0F, 3, 8, 1);
      TriangularFlagPart2.setRotationPoint(-8F, -1.5F, -1F);
      TriangularFlagPart2.setTextureSize(64, 32);
      TriangularFlagPart2.mirror = true;
      setRotation(TriangularFlagPart2, 0F, 0F, 0F);
      TriangularFlagPart3 = new ModelRenderer(this, 0, 0);
      TriangularFlagPart3.addBox(0F, 0F, 0F, 3, 7, 1);
      TriangularFlagPart3.setRotationPoint(-11F, -1F, -1F);
      TriangularFlagPart3.setTextureSize(64, 32);
      TriangularFlagPart3.mirror = true;
      setRotation(TriangularFlagPart3, 0F, 0F, 0F);
      TriangularFlagPart4 = new ModelRenderer(this, 0, 0);
      TriangularFlagPart4.addBox(0F, 0F, 0F, 2, 6, 1);
      TriangularFlagPart4.setRotationPoint(-13F, -0.5F, -1F);
      TriangularFlagPart4.setTextureSize(64, 32);
      TriangularFlagPart4.mirror = true;
      setRotation(TriangularFlagPart4, 0F, 0F, 0F);
      TriangularFlagPart5 = new ModelRenderer(this, 0, 0);
      TriangularFlagPart5.addBox(0F, 0F, 0F, 2, 5, 1);
      TriangularFlagPart5.setRotationPoint(-15F, 0F, -1F);
      TriangularFlagPart5.setTextureSize(64, 32);
      TriangularFlagPart5.mirror = true;
      setRotation(TriangularFlagPart5, 0F, 0F, 0F);
      TriangularFlagPart6 = new ModelRenderer(this, 0, 0);
      TriangularFlagPart6.addBox(0F, 0F, 0F, 1, 4, 1);
      TriangularFlagPart6.setRotationPoint(-16F, 0.5F, -1F);
      TriangularFlagPart6.setTextureSize(64, 32);
      TriangularFlagPart6.mirror = true;
      setRotation(TriangularFlagPart6, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5, int blockMetaData)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPole.png"));
    pole.render(f5);
    base.render(f5);
    Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/truk_texture.png"));
    top2.render(f5);
    top1.render(f5);
    top3.render(f5);
    if(blockMetaData == 1) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag.png"));
    if(blockMetaData == 2) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag2.png"));
    if(blockMetaData == 3) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag3.png"));
    if(blockMetaData == 4) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag4.png"));
    if(blockMetaData == 5) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag5.png"));
    if(blockMetaData == 6) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag6.png"));
    if(blockMetaData == 7) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag7.png"));
    if(blockMetaData == 8) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag8.png"));
    if(blockMetaData == 9) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag9.png"));
    if(blockMetaData == 10) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag10.png"));
    if(blockMetaData == 11) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag11.png"));
    if(blockMetaData == 12) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag12.png"));
    if(blockMetaData == 13) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag13.png"));
    if(blockMetaData == 14) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag14.png"));
    if(blockMetaData == 15) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag15.png"));
    if(blockMetaData == 16) Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("rep:textures/blocks/FlagPoleFlag16.png"));
    TriangularFlagPart1.render(f5);
    TriangularFlagPart2.render(f5);
    TriangularFlagPart3.render(f5);
    TriangularFlagPart4.render(f5);
    TriangularFlagPart5.render(f5);
    TriangularFlagPart6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
